/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myhilo;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.ArrayList;
import java.util.List;
import java.awt.Color;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.io.PrintStream;
/**
 *
 * @author hp
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    
    static List<String> username = new ArrayList<>();
    static List<String> password = new ArrayList<>();
    static List<Integer> userMoney = new ArrayList<>();
      public login() {
       
        setSize(500, 500);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Wrong = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        userText = new javax.swing.JTextField();
        goRegister = new javax.swing.JTextField();
        loginButt = new javax.swing.JButton();
        loginButt1 = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Wrong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Wrong.setForeground(new java.awt.Color(255, 255, 255));
        Wrong.setText("Wrong username or password");
        Wrong.setBorder(null);
        Wrong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Wrong.setFocusable(false);
        getContentPane().add(Wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        passwordText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordText.setForeground(new java.awt.Color(204, 204, 204));
        passwordText.setText("password");
        passwordText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTextMouseClicked(evt);
            }
        });
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 270, 40));

        userText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userText.setForeground(new java.awt.Color(204, 204, 204));
        userText.setText("username");
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTextMouseClicked(evt);
            }
        });
        getContentPane().add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 270, 40));

        goRegister.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        goRegister.setForeground(new java.awt.Color(102, 51, 255));
        goRegister.setText("Click here to create new account");
        goRegister.setToolTipText("");
        goRegister.setBorder(null);
        goRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goRegister.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goRegisterMouseClicked(evt);
            }
        });
        getContentPane().add(goRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 430, -1, -1));

        loginButt.setBackground(new java.awt.Color(102, 102, 255));
        loginButt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginButt.setForeground(new java.awt.Color(255, 255, 255));
        loginButt.setText("Login");
        loginButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtActionPerformed(evt);
            }
        });
        getContentPane().add(loginButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 120, 70));

        loginButt1.setBackground(new java.awt.Color(255, 51, 51));
        loginButt1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        loginButt1.setForeground(new java.awt.Color(255, 255, 255));
        loginButt1.setText("Cancel");
        loginButt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginButt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButt1ActionPerformed(evt);
            }
        });
        getContentPane().add(loginButt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 120, 70));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageStart/Login.png"))); // NOI18N
        Background.setText("0357102284");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMouseClicked
        userText.setText("");
        userText.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_userTextMouseClicked

    private void passwordTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextMouseClicked
        passwordText.setText("");
        passwordText.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_passwordTextMouseClicked

    private void goRegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goRegisterMouseClicked
         try {
            File theFile = new File("src/usernamepassword.log");
            Scanner fileScanner = new Scanner(theFile);
            while(fileScanner.hasNextLine()){
                String[] menu = fileScanner.nextLine().replaceAll(" : ","  ").split("  ");
                if(!menu[0].equals("##")) {
             username.add(menu[0]);
             password.add(menu[1]);
             userMoney.add(Integer.parseInt(menu[2]));
           }
            }
               

        } catch (FileNotFoundException e) {
            System.out.print(e);
        }
          
        registerForm regis = new registerForm();
        regis.setVisible(true);
    }//GEN-LAST:event_goRegisterMouseClicked

    private void loginButt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButt1ActionPerformed
        userText.setForeground(new java.awt.Color(204, 204, 204));
        userText.setText("username");
        passwordText.setForeground(new java.awt.Color(204, 204, 204));
        passwordText.setText("password");
    }//GEN-LAST:event_loginButt1ActionPerformed

    private void loginButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtActionPerformed
        
        String userLogin = userText.getText();
        String passLogin = passwordText.getText();
          try {
            File theFile = new File("src/usernamepassword.log");
            Scanner fileScanner = new Scanner(theFile);
            while(fileScanner.hasNextLine()){
                String[] menu = fileScanner.nextLine().replaceAll(" : ","  ").split("  ");
                if(!menu[0].equals("##")) {
             username.add(menu[0]);
             password.add(menu[1]);
             userMoney.add(Integer.parseInt(menu[2]));
           }
            }
               

        } catch (FileNotFoundException e) {
            System.out.print(e);
        }
        
        
        String logFilePath = "src/newfile.log";
        OutputStream os = null;
        try {
            os = new FileOutputStream(logFilePath);
        } catch (FileNotFoundException ex) {
            System.out.println("Couldn't open output file " + logFilePath);
            return;
        }
        PrintStream logSave = new PrintStream(os);
        
        for (int i = 0 ; i < username.size(); i++){
          if (userLogin.equals(username.get(i))&&passLogin.equals(password.get(i))){
              logSave.print(username.get(i)+" : "+password.get(i)+" : "+userMoney.get(i));
              StarForm start = new StarForm();
                
                start.setVisible(true);
                start.fileOpen();
                this.setVisible(false);
                
                logSave.close();
                break;
            }else{
              Wrong.setForeground(Color.RED);
          }
                
        }
    }//GEN-LAST:event_loginButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JTextField Wrong;
    private javax.swing.JTextField goRegister;
    private javax.swing.JButton loginButt;
    private javax.swing.JButton loginButt1;
    private javax.swing.JTextField passwordText;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
