/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myhilo;
import java.awt.Color;
import java.io.*;
import java.util.*;

/**
 *
 * @author hp
 */
public class RegisterForm extends javax.swing.JFrame {

    /**
     * Creates new form registerForm
     */
    LoginForm login = new LoginForm();
    public RegisterForm() {
        setSize(500, 500);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelButt = new javax.swing.JButton();
        regisButt = new javax.swing.JButton();
        userText = new javax.swing.JTextField();
        passwordText = new javax.swing.JTextField();
        passwordText1 = new javax.swing.JTextField();
        Wrong = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelButt.setBackground(new java.awt.Color(255, 51, 51));
        cancelButt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cancelButt.setForeground(new java.awt.Color(255, 255, 255));
        cancelButt.setText("Cancel");
        cancelButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 120, 70));

        regisButt.setBackground(new java.awt.Color(102, 102, 255));
        regisButt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        regisButt.setForeground(new java.awt.Color(255, 255, 255));
        regisButt.setText("Regis");
        regisButt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regisButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regisButtActionPerformed(evt);
            }
        });
        getContentPane().add(regisButt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 120, 70));

        userText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        userText.setForeground(new java.awt.Color(204, 204, 204));
        userText.setText("username");
        userText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userTextMouseClicked(evt);
            }
        });
        getContentPane().add(userText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 270, 40));

        passwordText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordText.setForeground(new java.awt.Color(204, 204, 204));
        passwordText.setText("password");
        passwordText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordTextMouseClicked(evt);
            }
        });
        getContentPane().add(passwordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 270, 40));

        passwordText1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        passwordText1.setForeground(new java.awt.Color(204, 204, 204));
        passwordText1.setText("retype password");
        passwordText1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                passwordText1MouseClicked(evt);
            }
        });
        getContentPane().add(passwordText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 210, 40));

        Wrong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Wrong.setForeground(new java.awt.Color(255, 255, 255));
        Wrong.setText("Retype password are not correct");
        Wrong.setBorder(null);
        Wrong.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Wrong.setFocusable(false);
        getContentPane().add(Wrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imageStart/register.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtActionPerformed
       this.setVisible(false);
    }//GEN-LAST:event_cancelButtActionPerformed

    private void userTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userTextMouseClicked
        userText.setText("");
        userText.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_userTextMouseClicked

    private void passwordTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordTextMouseClicked
        passwordText.setText("");
        passwordText.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_passwordTextMouseClicked

    private void passwordText1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_passwordText1MouseClicked
        passwordText1.setText("");
        passwordText1.setForeground(new java.awt.Color(0,0,0));
    }//GEN-LAST:event_passwordText1MouseClicked

    private void regisButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regisButtActionPerformed
        String logFilePath = "src/usernamepassword.log";
        OutputStream os = null;
        try {
            os = new FileOutputStream(logFilePath);
        } catch (FileNotFoundException ex) {
            System.out.println("Couldn't open output file " + logFilePath);
            return;
        }
        PrintStream logSave = new PrintStream(os);
        
        if (passwordText.getText().equals(passwordText1.getText())){
            for (int i = 0 ; i < login.username.size();i++){
            logSave.println(login.username.get(i)+" : "+login.password.get(i)+" : "+login.userMoney.get(i));
            }
            logSave.println(userText.getText()+" : "+passwordText.getText()+" : "+"2000");
            this.setVisible(false);
            login.username.clear();
            login.password.clear();
            login.userMoney.clear();
            NewMoneyAccount newmoney = new NewMoneyAccount();
            newmoney.setVisible(true);
        }else {
            Wrong.setForeground(Color.red);
        }
       logSave.close();
    
    }//GEN-LAST:event_regisButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Wrong;
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelButt;
    private javax.swing.JTextField passwordText;
    private javax.swing.JTextField passwordText1;
    private javax.swing.JButton regisButt;
    private javax.swing.JTextField userText;
    // End of variables declaration//GEN-END:variables
}
